name: Deploy
on: push

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Purge cache dekadence.ro
              uses: jakejarvis/cloudflare-purge-action@master
              env:
                  CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE_DEKADENCE_RO }}
                  CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}